---
sudo: false
language: c
matrix:
  include:
    - &ruby
      env: TEST=rubocop
      language: ruby
      rvm: '2.5'
      script: bundle exec rubocop

    - <<: *ruby
      env: TEST=rspec-bash
      script: bundle exec rspec --format doc

    - &plumb
      env: TEST=markdownlint
      language: c
      services:
        - docker
      script: ./tests/mdl.sh

    - <<: *plumb
      env: TEST=shellcheck
      script: ./tests/shellcheck.sh

    - <<: *plumb
      env: TEST=yamllint
      script: ./tests/yamllint.sh
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+\.\d+$/
notifications:
  email: false
